apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: resources-burner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: resources-burner
    app.kubernetes.io/part-of: resources-burner
  name: resources-burner
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: resources-burner
status:
  loadBalancer: {}
